/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kasir;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.JFrame;


/**
 *
 * @author Asus
 */
public class masuk extends javax.swing.JFrame {
    private koneksi dbConnection;
    
    private ResultSet rs = null;
    /**
     * Creates new form login
     */
    public masuk() {
        dbConnection = koneksi.getInstance();
        initComponents();
        this.setLocationRelativeTo(null);
        pnl_Overlay.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Overlay = new javax.swing.JPanel();
        pnl_Login = new javax.swing.JPanel();
        txt_Username = new javax.swing.JTextField();
        lab_Username = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lab_Password = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_Login = new javax.swing.JButton();
        lab_Note = new javax.swing.JLabel();
        lab_Note2 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        pnl_Overlay.setBackground(new java.awt.Color(51, 51, 51));
        pnl_Overlay.setForeground(new java.awt.Color(102, 102, 102));

        pnl_Login.setBackground(new java.awt.Color(0, 0, 0));
        pnl_Login.setForeground(new java.awt.Color(0, 255, 0));
        pnl_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Username.setBackground(new java.awt.Color(0, 0, 0));
        txt_Username.setForeground(new java.awt.Color(255, 255, 255));
        txt_Username.setBorder(null);
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });
        pnl_Login.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 238, -1));

        lab_Username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lab_Username.setForeground(new java.awt.Color(0, 153, 255));
        lab_Username.setText("Username");
        pnl_Login.add(lab_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 54, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnl_Login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 122, 238, 10));

        lab_Password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lab_Password.setForeground(new java.awt.Color(0, 153, 255));
        lab_Password.setText("Password");
        pnl_Login.add(lab_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 150, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        pnl_Login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 218, 238, 10));

        btn_Login.setBackground(new java.awt.Color(0, 153, 255));
        btn_Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        pnl_Login.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 262, 238, -1));

        lab_Note.setForeground(new java.awt.Color(255, 255, 255));
        lab_Note.setText("Don't have an account?");
        lab_Note.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_NoteMouseClicked(evt);
            }
        });
        pnl_Login.add(lab_Note, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 291, -1, -1));

        lab_Note2.setForeground(new java.awt.Color(0, 153, 255));
        lab_Note2.setText("Sign up");
        lab_Note2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_Note2MouseClicked(evt);
            }
        });
        pnl_Login.add(lab_Note2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 291, -1, -1));

        txt_Password.setBackground(new java.awt.Color(0, 0, 0));
        txt_Password.setForeground(new java.awt.Color(255, 255, 255));
        txt_Password.setBorder(null);
        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        pnl_Login.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 190, -1));

        javax.swing.GroupLayout pnl_OverlayLayout = new javax.swing.GroupLayout(pnl_Overlay);
        pnl_Overlay.setLayout(pnl_OverlayLayout);
        pnl_OverlayLayout.setHorizontalGroup(
            pnl_OverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_OverlayLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(pnl_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnl_OverlayLayout.setVerticalGroup(
            pnl_OverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_OverlayLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnl_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Overlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Overlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed

    private void lab_NoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_NoteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lab_NoteMouseClicked

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed

        if (!this.txt_Username.getText().isBlank() && !this.txt_Password.getText().isBlank()) {
            try {
                Statement st1 = dbConnection.getConnection().createStatement();
                String getAdmin = String.format("select * from login where username=\"%s\" and password=\"%s\";",
                        this.txt_Username.getText(), this.txt_Password.getText());
                ResultSet rs1 = st1.executeQuery(getAdmin);
                if (rs1.next()) {
                    dispose();
                    Transaksi mp = new Transaksi();
                    mp.setVisible(true);
                    mp.setExtendedState(mp.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                } else {
                    JOptionPane.showMessageDialog(this, "Maaf, data tersebut tidak tersedia di data admin!");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else if (this.txt_Username.getText().isBlank() && this.txt_Password.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mohon tidak mengosongkan input!");
        } else if (this.txt_Username.getText().isBlank() && !this.txt_Password.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Input Username kosong!");
        } else if (!this.txt_Username.getText().isBlank() && this.txt_Password.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Input Password kosong!");
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void lab_Note2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_Note2MouseClicked
        // TODO add your handling code here:
           openSignUpFrame();
    }

    // Metode untuk membuka JFrame SignUp
    private void openSignUpFrame() {
        signup signupFrame = new signup();
        signupFrame.setVisible(true); // Menampilkan JFrame SignUp
        this.dispose(); // Menutup JFrame Login
    
    }//GEN-LAST:event_lab_Note2MouseClicked

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masuk().setVisible(true);
            }
        });//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lab_Note;
    private javax.swing.JLabel lab_Note2;
    private javax.swing.JLabel lab_Password;
    private javax.swing.JLabel lab_Username;
    private javax.swing.JPanel pnl_Login;
    private javax.swing.JPanel pnl_Overlay;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
    
//    public void masukFunction() {
//    try {
//         
//        PreparedStatement pSt = koneksi.getInstance().getConnection().prepareStatement("SELECT * FROM login WHERE username =? and pass=?");
//
//        pSt.setString(1, txt_Username.getText()); 
//        pSt.setString(2, txt_Password.getText());
//        ResultSet rs = pSt.executeQuery();
//
//        if (rs.next()) {
//            JOptionPane.showMessageDialog(this, "Login Success!", "Information", JOptionPane.INFORMATION_MESSAGE);
//            String temp = rs.getString("id_login");
//        } else {
//            JOptionPane.showMessageDialog(this, "Username atau password salah!", "Login Failed!", JOptionPane.INFORMATION_MESSAGE);
//            txt_Password.setText("");
//        }
//        koneksi.getInstance().getConnection().close(); 
//    } catch (SQLException e) {
//        e.printStackTrace();
//    }
//}

    private void openTransaksi() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}

