/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kasir;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class signup extends javax.swing.JFrame {
    private koneksi dbConnection;

    /**
     * Creates new form signup
     */
    public signup() {
        dbConnection = koneksi.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lab_Title = new javax.swing.JLabel();
        lab_Nama = new javax.swing.JLabel();
        lab_Email = new javax.swing.JLabel();
        lab_Username = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Username = new javax.swing.JTextField();
        lab_Password = new javax.swing.JLabel();
        pass_Pasword = new javax.swing.JPasswordField();
        btn_Finish = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_Title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lab_Title.setForeground(new java.awt.Color(51, 153, 255));
        lab_Title.setText("Create Account");
        jPanel2.add(lab_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        lab_Nama.setForeground(new java.awt.Color(255, 255, 255));
        lab_Nama.setText("Nama");
        jPanel2.add(lab_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lab_Email.setForeground(new java.awt.Color(255, 255, 255));
        lab_Email.setText("Email");
        jPanel2.add(lab_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lab_Username.setForeground(new java.awt.Color(255, 255, 255));
        lab_Username.setText("Username");
        jPanel2.add(lab_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txt_Nama.setBackground(new java.awt.Color(51, 51, 51));
        txt_Nama.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nama.setBorder(null);
        txt_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NamaActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, 20));

        txt_Email.setBackground(new java.awt.Color(51, 51, 51));
        txt_Email.setForeground(new java.awt.Color(255, 255, 255));
        txt_Email.setBorder(null);
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, -1));

        txt_Username.setBackground(new java.awt.Color(51, 51, 51));
        txt_Username.setForeground(new java.awt.Color(255, 255, 255));
        txt_Username.setBorder(null);
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 190, -1));

        lab_Password.setForeground(new java.awt.Color(255, 255, 255));
        lab_Password.setText("Password");
        jPanel2.add(lab_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        pass_Pasword.setBackground(new java.awt.Color(51, 51, 51));
        pass_Pasword.setForeground(new java.awt.Color(255, 255, 255));
        pass_Pasword.setBorder(null);
        pass_Pasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_PaswordActionPerformed(evt);
            }
        });
        jPanel2.add(pass_Pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, -1));

        btn_Finish.setBackground(new java.awt.Color(51, 153, 255));
        btn_Finish.setForeground(new java.awt.Color(255, 255, 255));
        btn_Finish.setText("Finish");
        btn_Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FinishActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 163, 190, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 280, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NamaActionPerformed

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed

    private void pass_PaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_PaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_PaswordActionPerformed

    private void btn_FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FinishActionPerformed
        // TODO add your handling code here:
        openloginFrame();
    }                                          

    // Metode untuk membuka JFrame Login
    private void openloginFrame() {
        masuk loginFrame = new masuk();
        loginFrame.setVisible(true); // Menampilkan JFrame Login
        this.dispose(); // Menutup JFrame SignUp
                                              
    // Mendapatkan nilai dari field username dan password
    String username = txt_Username.getText();
    String password = new String(pass_Pasword.getPassword());

    // Memanggil metode untuk menyimpan data ke dalam database
    if (saveToDatabase(username, password)) {
        JOptionPane.showMessageDialog(this, "Registration Successful!", "Information", JOptionPane.INFORMATION_MESSAGE);
        // Jika registrasi berhasil, kembali ke JFrame Login
        new masuk().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Registration Failed!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Metode untuk menyimpan data ke dalam database
    private boolean saveToDatabase(String username, String password) {
        try {
            // Membuat koneksi ke database
            Statement st1 = dbConnection.getConnection().createStatement();

            // Menyiapkan query SQL untuk menyimpan data ke dalam tabel dblogin
            String query = String.format("INSERT INTO login (username, password) VALUES (\"%s\", \"%s\")", username, password);
            st1.executeUpdate(query);
            return true;
            // Mengeksekusi query untuk menyimpan data
            /*if (rowsAffected > 0) {
        // Dapatkan nilai id_login yang baru di-generate
            ResultSet generatedKeys = pStatement.getGeneratedKeys();
            if (generatedKeys.next()) {
            int newIdLogin = generatedKeys.getInt(1);
            System.out.println("New id_login: " + newIdLogin);
        }
    }       */
        // Mengembalikan nilai true jika data berhasil disimpan, false jika tidak
    } catch (SQLException e) {
        e.printStackTrace();
        return false; // Mengembalikan false jika terjadi kesalahan
    }


    }//GEN-LAST:event_btn_FinishActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Finish;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lab_Email;
    private javax.swing.JLabel lab_Nama;
    private javax.swing.JLabel lab_Password;
    private javax.swing.JLabel lab_Title;
    private javax.swing.JLabel lab_Username;
    private javax.swing.JPasswordField pass_Pasword;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
